name: Bolt-rs quality checks
on: [pull_request, create]

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Quality (clippy, rustfmt)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - stable
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy

      - name: Check commit formatting
        run: "pip3 install pytest && pytest -s $(find . -type f -name \"test_commit_format.py\")"

      - name: Formatting (rustfmt)
        run: cargo fmt -- --check

      - name: Clippy (all features)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run cargo unit tests
        run: cargo test
